### ISSUE TITLE
Licence

### ISSUE THREAD

**Issue by Jean-Baptiste-Camps** [Jean-Baptiste-Camps/stemmatology#16]
Our current license is deprecated and not so standard for R. Here is what R CMD check has to say:
````
Non-standard license specification:
  CC BY-NC-SA 2.0
Standardizable: FALSE
Deprecated license: CC BY-NC-SA 2.0
````
Should we switch to GPL or something like that ?

**Comment by floriancafiero** [comment]
The licenses considered as standard by R are listed here: https://www.r-project.org/Licenses/

Not a fan of BSD or LGPL, I would go for GPL-3 if it suits you, (Second best: AGPL ?).

**Comment by Jean-Baptiste-Camps** [comment]
Yes, we need a viral free license (I don't want to see derivatives in `privateur' software). I'm fine with GPL. Can you do the modification ?

**Comment by Jean-Baptiste-Camps** [comment]
Long since resolved…
