### ISSUE TITLE
Import.TEIApparatus

### ISSUE THREAD

**Issue by Jean-Baptiste-Camps** [Jean-Baptiste-Camps/stemmatology#19]
- Should we keep this function ?
- If yes, does it truly work ?
- If yes, document it !

**Comment by floriancafiero** [comment]
I am not very sure about this function, this could be useful in very specific cases, but even for TEI users, it could often prove to be of very little help. I would assign a low priority to solving this particular issue for the alpha, and try to implement it for a beta. It would then be good to think of a use-case we could write about.

**Comment by Jean-Baptiste-Camps** [comment]
Actually, we could maybe separate it, and just offer the XSLT stylesheet out of another repository (something like TEItoStemmatology or the like).

**Comment by Jean-Baptiste-Camps** [comment]
The use case is simple: I have a TEI encoded apparatus (common case…) and I want to do stemmatology on it. That's how I work now mainly.

**Comment by Jean-Baptiste-Camps** [comment]
Or a Collatex TEI output, that's not hard either.

**Comment by Jean-Baptiste-Camps** [comment]
Ok, I'm wondering again if we should keep this function. Pro's and con's:

Pro:

- not so hard to implement using `xslt` R package ( https://github.com/ropensci/xslt also on CRAN) and the stylesheet we already have;
- makes the life of user simpler (as getting the VL table might be an important bottleneck to using the package);

Con:

- makes the package dependent to more (heavy?) libraries (and consequently on their maintenance in the long term).

**Comment by Jean-Baptiste-Camps** [comment]
@floriancafiero , any thoughts on this one ?
