### ISSUE TITLE
Renaming functions

### ISSUE THREAD

**Issue by Jean-Baptiste-Camps** [Jean-Baptiste-Camps/stemmatology#2]
Two functions have been renamed, 

    PCC.elimination > PCC.overconflicting
    PCC.doElimination > PCC.elimination

The names now make more sense.
We need to:

- [x] rename them everywhere in the code;
- [x] rename the appropriate classes;
- [x] verify everything still works:
- [ ] check every names are satisfying and stop renaming functions…

As to what concerns the classes, they should change too in the following fashion:
    
    pccElimination > pccOverconflicting

**Comment by Jean-Baptiste-Camps** [comment]
On second thoughts, I wonder if it would not be easier to just integrate the very small PCC.doElimination, in PCC.elimination, and keep every name as is. Apparently, I had left a comment suggesting just that, and, Florian, you seem to think so too.

**Comment by Jean-Baptiste-Camps** [comment]
On third thoughts, I say: keep it. There are use cases where you want only an estimation of the overconflicting, and you may want to iterate this process with different thresholds, without actually suppressing anything from the database.

**Comment by Jean-Baptiste-Camps** [comment]
@floriancafiero , are you ok now with all the names, and can I close this ?

**Comment by floriancafiero** [comment]
Yep, let's close this :)
