### ISSUE TITLE
Conflicts graph

### ISSUE THREAD

**Issue by floriancafiero** [Jean-Baptiste-Camps/stemmatology#27]
We talked about improving the visualization of our graphs of conflicts. The current network is plotted with gplot (lines 284-285 in PCC.conflicts, as of today). 

`gplot(myNetwork, displaylabels, label = network.vertex.names(myNetwork), 
gmode = "graph", boxed.labels = TRUE)`

Other packages could give a more interesting output:
- The _networkD3_ package allows for interactive handling of networks, which could be useful to users handling a large database with many conflicting variant locations. 
- The _ggplot2_ package has become a reference, allows for extended possibilities compared to gplot. It could also be more perennial than networkD3, and produce easier to publish graphs.

**Comment by Jean-Baptiste-Camps** [comment]
For now, switched to igraph !
