### ISSUE TITLE
Documentation and packaging

### ISSUE THREAD

**Issue by Jean-Baptiste-Camps** [Jean-Baptiste-Camps/stemmatology#8]
We have to finish documentation and package the code.

**Comment by Jean-Baptiste-Camps** [comment]
- [ ] Document functions
- [ ] Document data-sets;
- [ ]  Document package ;
For packaging
- [ ] Check package integrity ;
- [ ] package !

**Comment by floriancafiero** [comment]
Etat des lieux:

* Import. TEIApparatus
→ à faire entièrement

* PCC.Stemma
→ manquent titre, description et value

* PCC.buildgroup
→ manquent titre et références (value? - pas pertinent?)

* PCC.contam
→ manquent titre et références

* PCC.disagreement
→ manquent titre et références

* PCC.distribute
→ manquent titres, arguments, value et références

* PCC .conflicts
→ Manquent titre et références

*PCC.reconstructModel
→ manquent titre, value et références

Good as they are :
PCC, PCC.Exploratory, PCC. Conflicts, PCC.overconflicting, PCC.elimination

**Comment by Jean-Baptiste-Camps** [comment]
We need also to add examples in the functions documentation. This is also useful to do some testing, as examples are run during package integrity checks. Right now, it will be possible maybe only for low level functions (for the higher level, we will need #4 ).

**Comment by Jean-Baptiste-Camps** [comment]
I'll close this, and we will open more specific issues for documentation specifics.
